### PR TITLE
Leaderboard: hit the API

### PR DESCRIPTION
**Pull request by Stephen-Adom**
# Leaderboard: Hit the API
In this pull request, the following tasks were implemented:
- create services for fetching and adding scores and creating games.
- implement add scores when the user enters name and score
- implement the refresh function to refresh the scores list
- Used fetch, async and await and callback functions to implement leaderboard functionalities

### CODE REVIEW

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
## Hi @Stephen-Adom  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!



## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] While you did a wonderful job with the API, kindly make sure to implement the "Refresh" button that will get all scores for a game created by you from the API (receiving data from the API and parsing the JSON, not from the LocalStorage).

https://user-images.githubusercontent.com/105117832/223721999-4d12ab31-0e26-48bd-96f7-a6241e25c3e8.mp4



- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Stephen-Adom** [comment]
Hello @IngDavidTM,
- The refresh button implementation already fetches from the API and updates the local storage then the `renderScoresInDOM` function rerenders the updated store. Please check the code to verify the data updates.
- Also from the video, you didn't verify the implementation of the refresh button to check if it's being fetched from the API. You also cleared the local storage which will generate a new id for the requests when there's no id.

**Comment by Stephen-Adom** [comment]
> ## Hi @Stephen-Adom 🙋‍♂️,
> Good job so far! You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!
> 
>  [ 68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f333151333645484a3743355a6f494d7737392f67697068792e676966 ](https://camo.githubusercontent.com/78087f8205c5736aa2d7d71fc32f3ec42ca7302de1c46e79464a18f3fba32dfb/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f333151333645484a3743355a6f494d7737392f67697068792e676966) [ ](https://camo.githubusercontent.com/78087f8205c5736aa2d7d71fc32f3ec42ca7302de1c46e79464a18f3fba32dfb/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f333151333645484a3743355a6f494d7737392f67697068792e676966)
> 
> ## Top highlight 🎯
> * The Pull Request follows the GitHub Flow ✅
> * The PR title and description are professional and descriptive ✅
> * Linters are working properly ✅
> 
> ## Suggested changes
> * [ ]  While you did a wonderful job with the API, kindly make sure to implement the "Refresh" button that will get all scores for a game created by you from the API (receiving data from the API and parsing the JSON, not from the LocalStorage).
> 
> * [x]  _Check the comments under the review._ ⬇
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by binhussen — COMMENTED** [review]
Hi @Stephen-Adom , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
